# Generated by Django 4.2.2 on 2023-06-11 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('report_datetime', models.DateTimeField()),
                ('pulce', models.IntegerField()),
                ('preassure1', models.IntegerField()),
                ('preassure2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime(2023, 6, 11, 19, 8, 58, 952848))),
                ('weight', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=0)),
            ],
        ),
    ]
