# Generated by Django 4.2.2 on 2023-06-11 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 11, 19, 9, 46, 263323)),
        ),
    ]
