# Generated by Django 4.2.2 on 2023-06-11 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userinfo_options_alter_userinfo_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalinfo',
            options={'verbose_name': "User's medical info", 'verbose_name_plural': "Users' medical info"},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User info', 'verbose_name_plural': 'Users info'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 11, 19, 22, 29, 988964)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
