# Generated by Django 4.2.2 on 2023-06-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_medicalinfo_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 11, 19, 27, 55, 153426)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=0),
        ),
    ]
