# Generated by Django 4.2.2 on 2023-06-11 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userinfo_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 6, 11)),
        ),
    ]
