# Generated by Django 4.2.2 on 2023-06-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userinfo_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='pulce',
            new_name='pulse',
        ),
    ]
