# Generated by Django 4.2.2 on 2023-06-12 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_pulce_medicalinfo_pulse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='pulse',
            new_name='preassure3',
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='preassure4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='pulse1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='pulse2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 6, 12)),
        ),
    ]
