# Generated by Django 4.2.2 on 2023-06-14 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_message_rename_pulse_medicalinfo_preassure3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='message',
            field=models.TextField(default='Вы еще не отправляли ни одного отчета'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 6, 14)),
        ),
    ]
